apiVersion: apps/v1
kind: Deployment
metadata:
  name: lgtm
  namespace: lgtm
  labels:
    app: lgtm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lgtm
  template:
    metadata:
      labels:
        app: lgtm
    spec:
      containers:
      - name: lgtm
        image: grafana/otel-lgtm:latest
        ports:
          - name: grafana
            containerPort: 3000
            protocol: TCP
          - name: otlp-grpc
            containerPort: 4317
            protocol: TCP
          - name: otlp-http
            containerPort: 4318
            protocol: TCP
        env:
          - name: GOMAXPROCS
            valueFrom:
              resourceFieldRef:
                containerName: lgtm
                resource: limits.cpu
        resources:
          requests:
            cpu: 500m
            memory: 1Gi
          limits:
            cpu: 2000m
            memory: 4Gi
