apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Base Kubernetes configuration
resources:
  - ../kubernetes

# AWS-specific patches
patches:
  - path: grafana-loadbalancer.yaml
  - path: loggen-pod-affinity.yaml

# Use ECR image instead of GHCR
images:
  - name: ghcr.io/ollygarden/thyme
    newName: 061039797035.dkr.ecr.eu-central-1.amazonaws.com/thyme
    newTag: build-1771920596
